version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres.mutevazipeynircilik.com  #6th commit
      - DB_Pwd=admadmadm3
      - REDIS_Pwd=
      - JWT_SECRET=
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: customers
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass 
    ports:
      - "6379:6379"

volumes:
  postgres_data:
